services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres6910
      - POSTGRES_DB=university
    ports:
      - "5436:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres6910_test
      - POSTGRES_DB=university_test
    ports:
      - "5437:5432"
    networks:
      - custom
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - custom
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_storage:/var/lib/grafana
    depends_on:
      - prometheus
    restart: always
    networks:
      - custom
    user: "0"
networks:
  custom:
    driver: bridge
