services:
  db:
    container_name: "db"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres6910
      - POSTGRES_DB=university
    ports:
      - "5436:5432"
    networks:
      - custom
  db_test:
    container_name: "db_test"
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres_test
      - POSTGRES_PASSWORD=postgres6910_test
      - POSTGRES_DB=university_test
    ports:
      - "5437:5432"
    networks:
      - custom
networks:
  custom:
    driver: bridge
