"""create table for users

Revision ID: 11e6e29ebd66
Revises: 629d642929b5
Create Date: 2025-03-07 18:21:04.223422

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "11e6e29ebd66"
down_revision: Union[str, None] = "629d642929b5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
