"""create table for users

Revision ID: 3153f9451de0
Revises: 939ff93e9ce8
Create Date: 2025-03-08 19:36:45.867401

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "3153f9451de0"
down_revision: Union[str, None] = "939ff93e9ce8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
