"""create table for users

Revision ID: 51bcb52e2e8f
Revises: 9970a1fb138a
Create Date: 2025-03-07 17:05:48.518352

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "51bcb52e2e8f"
down_revision: Union[str, None] = "9970a1fb138a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
