"""create table for users

Revision ID: 69065286201d
Revises: f4d77284a651
Create Date: 2025-03-07 16:53:32.945827

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "69065286201d"
down_revision: Union[str, None] = "f4d77284a651"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
