"""create table for users

Revision ID: 75e8d9e5291f
Revises: 7cc582d7e620
Create Date: 2025-03-07 18:15:44.497751

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "75e8d9e5291f"
down_revision: Union[str, None] = "7cc582d7e620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
