"""create table for users

Revision ID: 7b32a45af37f
Revises: 69065286201d
Create Date: 2025-03-07 16:55:26.124484

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "7b32a45af37f"
down_revision: Union[str, None] = "69065286201d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
