"""create table for users

Revision ID: 939ff93e9ce8
Revises: 5891b2662351
Create Date: 2025-03-08 19:34:43.061814

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "939ff93e9ce8"
down_revision: Union[str, None] = "5891b2662351"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
