"""create table for users

Revision ID: a48454af72bc
Revises: af1924bc11de
Create Date: 2025-03-08 19:06:40.496456

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "a48454af72bc"
down_revision: Union[str, None] = "af1924bc11de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
