"""create table for users

Revision ID: bbb553abc066
Revises: d62aeff77864
Create Date: 2025-03-07 17:44:37.101290

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "bbb553abc066"
down_revision: Union[str, None] = "d62aeff77864"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
