"""create table for users

Revision ID: eb5b693a7e04
Revises: eb35f706db14
Create Date: 2025-03-07 17:23:22.936329

"""
from typing import Sequence
from typing import Union


# revision identifiers, used by Alembic.
revision: str = "eb5b693a7e04"
down_revision: Union[str, None] = "eb35f706db14"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
